[1,"- The project is out-of-sync -- use `\u001B]8;;x-r-run:renv::status()\u0007renv::status()\u001B]8;;\u0007` for details.\r\n"]
[1,"\u001B[31merror\u001B[39m\u001B[31m: Uncaught (in promise) YAMLException: bad indentation of a mapping entry (13:16)\r\n"]
[1,"\r\n"]
[1," 10 |   - name: Tran Quoc Hoang\r\n"]
[1," 11 |     student_id: BTBTWE24036 # Custom field for ID\r\n"]
[1," 12 | affiliation: School of Biotechnology, Internat ...\r\n"]
[1," 13 | course: BT335IU: Immunology\r\n"]
[1,"---------------------^\r\n"]
[1," 14 | instructor: Assoc. Prof. Hoai T. T. Nguyen\r\n"]
[1," 15 | date: today\r\n"]
[1,"    return new exception1(message, mark);\r\n"]
[1,"           ^\r\n"]
[1,"    at generateError1 (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:18079:12)\r\n"]
[1,"    at throwError1 (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:18082:11)\r\n"]
[1,"    at readBlockMapping1 (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:18750:13)\r\n"]
[1,"    at composeNode1 (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:18925:85)\r\n"]
[1,"    at readDocument1 (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:19055:5)\r\n"]
[1,"    at loadDocuments1 (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:19097:9)\r\n"]
[1,"    at load$11 (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:19115:21)\r\n"]
[1,"    at parseWithNiceErrors (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:19870:16)\r\n"]
[1,"    at readYamlFromMarkdown (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:19801:17)\r\n"]
[1,"    at markdownExecutionEngine (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:42144:20)\r\n"]
[1,"\u001B[39m"]
[1,"\u001B[1m\u001B[33mError\u001B[39m in `quarto::quarto_render()`:\u001B[22m\r\n"]
[1,"\u001B[1m\u001B[22m\u001B[33m!\u001B[39m Error running quarto CLI from R.\r\n"]
[1,"\u001B[1mCaused by error in `quarto::quarto_render()`:\u001B[22m\r\n"]
[1,"\u001B[1m\u001B[22m\u001B[31m✖\u001B[39m Error returned by quarto CLI.\r\n"]
[1,"  -----------------------------\r\n"]
[1,"  error: Uncaught (in promise) YAMLException: bad indentation of a mapping\r\n"]
[1,"  entry (13:16)\r\n"]
[1,"  \r\n"]
[1,"  10 | - name: Tran Quoc Hoang\r\n"]
[1,"  11 | student_id: BTBTWE24036 # Custom field for ID\r\n"]
[1,"  12 | affiliation: School of Biotechnology, Internat ...\r\n"]
[1,"  13 | course: BT335IU: Immunology\r\n"]
[1,"  ---------------------^\r\n"]
[1,"  14 | instructor: Assoc. Prof. Hoai T. T. Nguyen\r\n"]
[1,"  15 | date: today\r\n"]
[1,"  return new exception1(message, mark);\r\n"]
[1,"  ^\r\n"]
[1,"  at generateError1 (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:18079:12)\r\n"]
[1,"  at throwError1 (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:18082:11)\r\n"]
[1,"  at readBlockMapping1 (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:18750:13)\r\n"]
[1,"  at composeNode1 (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:18925:85)\r\n"]
[1,"  at readDocument1 (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:19055:5)\r\n"]
[1,"  at loadDocuments1 (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:19097:9)\r\n"]
[1,"  at load$11 (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:19115:21)\r\n"]
[1,"  at parseWithNiceErrors (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:19870:16)\r\n"]
[1,"  at readYamlFromMarkdown (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:19801:17)\r\n"]
[1,"  at markdownExecutionEngine (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:42144:20)\r\n"]
[1,"  \r\n"]
[1,"\u001B[1mCaused by error:\u001B[22m\r\n"]
[1,"\u001B[33m!\u001B[39m System command 'quarto.exe' failed\r\n"]
[1,"Backtrace:\r\n"]
[1,"\u001B[90m     \u001B[39m▆\r\n"]
[1,"\u001B[90m  1. \u001B[39m├─.rs.sourceWithProgress(...)\r\n"]
[1,"\u001B[90m  2. \u001B[39m│ └─\u001B[1mbase\u001B[22m::eval(statements[[idx]], envir = globalenv())\r\n"]
[1,"\u001B[90m  3. \u001B[39m│   └─base::eval(statements[[idx]], envir = globalenv())\r\n"]
[1,"\u001B[90m  4. \u001B[39m├─\u001B[1m\u001B[94mquarto::quarto_render(\u001B[39m\u001B[22m\u001B[1m\u001B[94m)\u001B[39m\u001B[22m\r\n"]
[1,"\u001B[90m  5. \u001B[39m│ └─quarto:::quarto_run(args, echo = TRUE, quarto_bin = quarto_bin)\r\n"]
[1,"\u001B[90m  6. \u001B[39m│   ├─\u001B[1mbase\u001B[22m::withCallingHandlers(...)\r\n"]
[1,"\u001B[90m  7. \u001B[39m│   └─\u001B[1mprocessx\u001B[22m::run(...)\r\n"]
[1,"\u001B[90m  8. \u001B[39m│     └─throw(...)\r\n"]
[1,"\u001B[90m  9. \u001B[39m│       └─\u001B[1mbase\u001B[22m::signalCondition(cond)\r\n"]
[1,"\u001B[90m 10. \u001B[39m└─\u001B[1mquarto\u001B[22m (local) `<fn>`(`<S3: system_command_status_error>`)\r\n"]
[1,"\u001B[90m 11. \u001B[39m  └─quarto:::wrap_quarto_error(e, args, .call = .call)\r\n"]
[1,"\u001B[90m 12. \u001B[39m    └─\u001B[1mcli\u001B[22m::cli_abort(msg, call = .call, parent = cnd, )\r\n"]
[1,"\u001B[90m 13. \u001B[39m      └─\u001B[1mrlang\u001B[22m::abort(...)\r\n"]
[2,"Execution halted\r\n"]
